# Generated by Django 5.1.5 on 2025-03-24 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='main_student',
        ),
    ]
