# Generated by Django 5.2 on 2025-04-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_currentprice_purchase_delete_stockprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['stock', 'buy_price'], name='main_purcha_stock_i_bc479a_idx'),
        ),
    ]
